CREATE TABLE IF NOT EXISTS users (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  user_name     VARCHAR(100) NOT NULL,
  password      VARCHAR(255) NOT NULL,
  email         VARCHAR(150) NOT NULL UNIQUE,
  phone_number  VARCHAR(15)  NOT NULL,
  role          ENUM('Admin', 'Staff') NOT NULL DEFAULT 'Admin',
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
